language: java

dist: xenial

git:
  depth: false

node_js:
  - "10"

addons:
  sonarcloud:
    organization: "alessandroferi"
    
services: 
  - xvfb
  - docker
  
env: DISPLAY=:99.0

before_script:
 - sh -e /etc/init.d/xvfb start

    
install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache 
    
script:
  - mvn -f bookshop-project2/pom.xml clean verify -Pjacoco coveralls:report sonar:sonar
  #- mvn -f bookshop-project2/pom.xml verify -Pintegration-tests
  #- mvn -f bookshop-project2/pom.xml verify -Pe2e-tests
  #- mvn -f bookshop-project2/pom.xml verify -Pmutation-testing